name: Docker Compose CI

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and start services
        run: docker compose -f compose.yml -f .ci/compose-vpn-test.yml up --build -d

      - name: Check VPN connection
        run: |
          docker compose exec -d vpn-test openconnect --protocol=anyconnect --user=test --passwd-on-stdin --servercert pin-sha256:BxSbjiiFR6PSD6O8DJ2fRFLXEG5ROLGQZAjWqmGFrlo= ocserv:443 <<< "test1" &
          sleep 10

      - name: Check internet access through VPN
        run: |
          docker compose exec vpn-test curl -s https://api.ipify.org
      - name: Stop and remove containers
        run: docker compose down
